#!/bin/bash

# bare minimum needed to work
if [ -z "$CTL_ROOT" ]; then
  echo "$(basename $0): CTL_ROOT undefined" 2>&1
  exit 1
fi
if [ -z "$CTL_ENV" ]; then
  echo "$(basename $0): CTL_ENV undefined" 2>&1
  exit 1
fi

# grab environment
source "$CTL_ENV"

# source our bash library
source "$CTL_BASH_LIB"

# verbose mode?
v=0

# parse args
while [ $# -ne 0 ]; do
  case "$1" in
    -v|--verbose)
      v=1
      shift
      ;;
    *)
      arg_bad "$1"
      ;;
  esac
done

# print message if in verbose mode
#
# args:
#  @msg: message
verbose() {
  local msg="$1"

  if [ $v != 0 ]; then
    do_or_die echo "$(basename $0): $msg"
  fi
}

# switch to our directory
docdir=$(dirname $0)
verbose "switching to $docdir"
cd "$docdir"

# templates
tmps=(
  'arr' # dynamic array
)

for ((i = 0; i < ${#tmps[@]}; i++)); do
  verbose "tmps[$i] = \"${tmps[i]}\""
done

verbose 'generating doc for each list template...'
# for each template
for ((i = 0; i < ${#tmps[@]}; i++)); do
  tmp="${tmps[i]}"               # template name
  hdr="../../hdr/list/$tmp"      # template doc header
  udir="$CTL_ARCH/user/list"     # user doc directory
  idir="$CTL_ARCH/internal/list" # internal doc directory
  tmpsrc="$CTL_TMP/list/$tmp.h"  # template source
  func="CTL_${tmp^^}_DEF"        # template function name
  idoc="$idir/$tmp"              # internal doc
  udoc="$udir/$tmp"              # user doc

  verbose "tmps[$i].name = \"$tmp\""
  verbose "tmps[$i].func = \"$func\""
  verbose "tmps[$i].udoc = \"$udoc\""
  verbose "tmps[$i].idoc = \"$idoc\""
  verbose "tmps[$i].hdr  = \"$hdr\""
  verbose "tmps[$i].src  = \"$tmpsrc\""

  # fail if no header
  if ! [ -f "$hdr" ]; then
    die "\"$tmp\" does not have a header yet"
  fi

  # setup user doc for template
  verbose "setting up user doc directory for $tmp"
  mkdir_if_not "$udir"

  # setup internal doc for template
  verbose "setting up internal doc directory for $tmp"
  mkdir_if_not "$idir"

  # write header to internal doc
  verbose "copying \"$hdr\" to \"$idoc\""
  do_or_die echo -e "$CTL_AUTO_GEN_MSG\n" >"$idoc"
  do_or_die cat "$hdr" >>"$idoc"
  do_or_die echo >>"$idoc"

  # write header to user doc
  verbose "copying \"$hdr\" to \"$udoc\""
  do_or_die echo -e "$CTL_AUTO_GEN_MSG\n" >"$udoc"
  do_or_die cat "$hdr" >>"$udoc"
  do_or_die echo >>"$udoc"

  # generate template doc
  verbose "running \"./list.awk\" on \"$tmpsrc\" with FUNC=\"$func\", UDOC=\"$udoc\", IDOC=\"$idoc\""
  do_or_die ./list.awk \
    -v FUNC="$func"    \
    -v UDOC="$udoc"    \
    -v IDOC="$idoc"    \
    "$tmpsrc"

  verbose "removing last line in $udoc"
  do_or_die sed -i '$d' "$udoc"

  verbose "removing last line in $idoc"
  do_or_die sed -i '$d' "$idoc"

  verbose "\"$tmp\" doc created"
done
