#!/bin/bash

# run command line and die if it fails:
#
# args:
#  @cmd: command line
do_or_die() {
  "$@"
  local stat=$?
  if [ $stat -ne 0 ]; then
    echo "command failed: $@" >&2
    exit $stat
  fi
}

# write message to stderr:
#
# args:
#  @msg: message to write
stderr() {
  do_or_die printf "$1" >&2
  do_or_die printf "\n"
}

# print message to stderr and exit
#
# args:
#  @msg:  message
#  @code: exit code
#
# ret:
#  exit process
die() {
  local msg="$1"
  local code="$2"

  stderr "$msg"
  exit "$code"
}

# called when script hits bad argument
#
# args:
#  @arg:  offending argument
#  @path: path of script
#
# ret:
#  exit process
arg_bad() {
  local arg="$1"
  local path="$2"

  case "$arg" in
    -*)
      die "$(basename $path): invalid option: $arg" "$CTL_OPT_BAD"
      ;;
    *)
      die "$(basename $path): unexpected positional paramter: $arg" "$CTL_OPT_POS"
      ;;
  esac

  die "arg_bad: argument is not invalid"
}
