#!/bin/bash

# run command line and die if it fails:
#
# args:
#  @cmd: command line
do_or_die() {
  "$@"
  local stat=$?
  if [ $stat -ne 0 ]; then
    echo "command failed: $@" >&2
    exit $stat
  fi
}

# write message to stderr:
#
# args:
#  @msg: message to write
stderr() {
  do_or_die printf "$1" >&2
  do_or_die printf "\n"
}

# write message to stderr if v != 0:
#
# args:
#  @msg: message to write
#  @v:   verbose mode?
do_verbose() {
  local msg="$1"
  local v="$2"

  if [ "$v" -ne 0 ]; then
    stderr "$msg"
  fi
}
