#!/bin/bash

# bare minimum needed to work
if [ -z "$CTL_ROOT" ]; then
  echo "run_tests: CTL_ROOT undefined" 2>&1
  exit 1
fi
if [ -z "$CTL_ENV" ]; then
  echo "run_tests: CTL_ENV undefined" 2>&1
  exit 1
fi

# source our environment
source "$CTL_ENV"

# source our bash library
source "$CTL_BASH_LIB"

# verbose mode?
v=

# performance test?
perf_test=

# silent mode?
silent=

# parse args
while [ $# -ne 0 ]; do
  case "$1" in
    -v|--verbose)
      v='-v'
      shift
      ;;
    -s|--silent)
      silent='-s'
      shift
      ;;
    -p|--perf)
      perf_test='-p'
      shift
      ;;
    *)
      arg_bad "$1"
      ;;
  esac
done

do_or_die ./doc/doc $v
do_or_die ./run_tests $v $silent $perf_test
