#!/bin/bash

# source our environment
source "$CTL_ENV"

# source our bash library
source "$CTL_BASH_LIB"

# switch to our directory
docdir=$(dirname $0)
cd "$docdir"

# make sure we have packages we need
pkg=(
  'bash' '--version'  '5.1.16(1)-release'
  'tree' '--version'  'v2.0.2'
  'make' '--version'  '4.3'
  'gcc'  '--version'  '11.4.0'
)
for ((p = 0; p < ${#pkg[@]}; p += 3)); do
  cmd="${pkg[p]}"
  opt="${pkg[p + 1]}"
  v="${pkg[p + 2]}"
  re=$(echo "$v" | sed 's/\./\\./g')
  if ! "$cmd" "$opt" | head -1 | grep "$re" >/dev/null 2>&1; then
    die "require $cmd version $v"
  fi
done
# mawk does not like ^^^ so have to do it separate
if ! mawk -W v 2>/dev/null | head -1 | grep '1\.3\.4' >/dev/null; then
  die 'require mawk version 1.3.4'
fi

# verbose mode?
v=

# performance test?
perf_test=

# silent mode?
silent=

# parse args
while [ $# -ne 0 ]; do
  case "$1" in
    -v|--verbose)
      v='-v'
      shift
      ;;
    -s|--silent)
      silent='-s'
      shift
      ;;
    -p|--perf)
      perf_test='-p'
      shift
      ;;
    *)
      arg_bad "$1"
      ;;
  esac
done

do_or_die ./doc/doc $v
do_or_die ./test/run $v $silent $perf_test
