#!/bin/bash

# bare minimum needed to work
if [ -z "$CTL_ROOT" ]; then
  echo "mkarrtest: CTL_ROOT undefined" 2>&1
  exit 1
fi
if [ -z "$CTL_ENV" ]; then
  echo "mkarrtest: CTL_ENV undefined" 2>&1
  exit 1
fi

# grab environment
source "$CTL_ENV"

# bring in library
source "$CTL_BASH_LIB"

# silent mode?
silent=0

# parse args
while [ $# -ne 0 ]; do
  case "$1" in
    -s|--silent)
      silent=1
      shift
      ;;
    -*)
      arg_bad "$1"
      ;;
    *)
      break
      ;;
  esac
done

# switch to our directory
docdir=$(dirname $0)
cd "$docdir"

do_or_die echo -e "/* $CTL_AUTO_GEN_MSG */\n" >"$CTL_TEST/do/arr.c"
do_or_die echo "#include \"$CTL_LIB/lib.h\"" >>"$CTL_TEST/do/arr.c"
do_or_die echo "#include \"$CTL_TMP/arr.h\"" >>"$CTL_TEST/do/arr.c"
do_or_die echo "#include <time.h>" >>"$CTL_TEST/do/arr.c"
do_or_die echo -e "#include <stdlib.h>\n" >>"$CTL_TEST/do/arr.c"

do_or_die ./gen.awk -v SILENT=$silent "./tab/arr" >>"$CTL_TEST/do/arr.c"
