#!/bin/bash

# grab environment
source "$CTL_ENV"

# source our bash library
source "$CTL_BASH_LIB"

# verbose mode?
v=

# parse args
while [ $# -ne 0 ]; do
  case "$1" in
    -v|--verbose)
      v='-v'
      shift
      ;;
    *)
      arg_bad "$1"
      ;;
  esac
done

# print message if in verbose mode
#
# args:
#  @msg: message
verbose() {
  local msg="$1"

  if [ -n "$v" ]; then
    do_or_die echo "$(basename $0): $msg"
  fi
}

# switch to our directory
docdir=$(dirname $0)
verbose "switching to $docdir"
cd "$docdir"

verbose 'generating docs...'

# setup arch directory if needed
verbose "setting up arch directory"
mkdir_if_not "$CTL_ARCH"

# setup internal doc directory
verbose "setting up internal docs"
mkdir_if_not "$CTL_ARCH/internal"

# generate directory tree picture
verbose "generating directory tree picture"
do_or_die echo -e "$CTL_AUTO_GEN_MSG\n"  >"$CTL_ARCH/internal/pic"
do_or_die tree "$CTL_ROOT" >>"$CTL_ARCH/internal/pic"

# generate env doc
verbose "generating env doc..."
do_or_die echo -e "$CTL_AUTO_GEN_MSG\n" >"$CTL_ARCH/internal/env"
do_or_die ./env.awk "$CTL_ENV" >>"$CTL_ARCH/internal/env"

# generate user docs
verbose "setting up user doc directory"
mkdir_if_not "$CTL_ARCH/user"

verbose 'generating doc for each template...'
do_or_die ./tmp/list/list $v
do_or_die ./tmp/map/hash/hash $v
